# Generated by Django 3.2.5 on 2021-08-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='videos/%Y/%m/%d')),
                ('status', models.CharField(default='waiting', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('current_progress', models.IntegerField(blank=True, default=0)),
                ('faces_count', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Загруженные видео',
            },
        ),
    ]
